export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";

export const PRODUCT_BY_ID = "PRODUCT_BY_ID";
export const PRODUCT_BY_ID_SUCCESS = "PRODUCT_BY_ID_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const EDIT_CART_PRODUCT_QUANTITY = "EDIT_CART_PRODUCT_QUANTIT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART = "UPDATE_CART";

export const ALL_PHARMACIES = "ALL_PHARMACIES";
export const ALL_PHARMACIES_SUCCESS = "ALL_PHARMACIES_SUCCESS";

export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";

export const CATEGORY = "CATEGORY";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const LOAD_DASH_COMPONENT = "LOAD_DASH_COMPONENT";
export const LOADED_DASH_COMPONENT = "LOADED_DASH_COMPONENT";

export const UPDATE_URL = "UPDATE_URL";
export const UPDATE_USER = "UPDATE_USER";

export const UPDATE_MERCHANT = "UPDATE_MERCHANT";
export const UPDATE_MERCHANT_PRODUCTS = "UPDATE_MERCHANT_PRODUCTS";
